"""initial schema

Revision ID: c6f303a1b05c
Revises: 
Create Date: 2026-04-01 16:27:24.188591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6f303a1b05c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('sic_code', sa.String(length=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cik')
    )
    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('filings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('accession_number', sa.String(length=25), nullable=False),
    sa.Column('form_type', sa.String(length=10), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('document_url', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accession_number')
    )
    op.create_index('ix_filings_company_date', 'filings', ['company_id', 'filing_date'], unique=False)
    op.create_table('watchlist_companies',
    sa.Column('watchlist_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ),
    sa.PrimaryKeyConstraint('watchlist_id', 'company_id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_company_created', 'alerts', ['company_id', 'created_at'], unique=False)
    op.create_table('drift_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.Column('prev_filing_id', sa.Integer(), nullable=False),
    sa.Column('section_type', sa.String(length=50), nullable=False),
    sa.Column('cosine_distance', sa.Float(), nullable=True),
    sa.Column('jaccard_distance', sa.Float(), nullable=True),
    sa.Column('added_words', sa.Integer(), nullable=True),
    sa.Column('removed_words', sa.Integer(), nullable=True),
    sa.Column('sentiment_delta', sa.JSON(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.ForeignKeyConstraint(['prev_filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filing_id', 'section_type', name='uq_drift_filing_section')
    )
    op.create_table('key_phrases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.Column('section_type', sa.String(length=50), nullable=False),
    sa.Column('phrase', sa.String(length=200), nullable=False),
    sa.Column('first_seen_filing_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.ForeignKeyConstraint(['first_seen_filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.Column('section_type', sa.String(length=50), nullable=False),
    sa.Column('section_text', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('embedding', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filing_id', 'section_type', name='uq_section_filing_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sections')
    op.drop_table('key_phrases')
    op.drop_table('drift_scores')
    op.drop_index('ix_alerts_company_created', table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('watchlist_companies')
    op.drop_index('ix_filings_company_date', table_name='filings')
    op.drop_table('filings')
    op.drop_table('watchlists')
    op.drop_table('companies')
    # ### end Alembic commands ###
